---
title: "Ice Cover"
format: html
editor: visual
---



```{r}
library(tidyverse)
library(here)
library(ggbeeswarm)
library(ggExtra)
```

## Read in Data

```{r}
weather_data <- read_csv(here("data", "ntl20_v6.csv"), na = "-999")
ice_data <- read_csv(here("data", "ntl33_v7.csv"), na = "-999")

```

```{r}
ice_duration_plot <- ggplot(data = ice_data, aes(x = lakeid,
                                            y = ice_duration)) +
  geom_beeswarm(size = 0.5) +
  geom_boxplot(fill = NA, outlier.shape = NA)

ice_duration_plot
```

```{r}
mean_ice_cover <- ice_data |> 
  group_by(year4) |> 
  summarize(mean_ice_duration = round(mean(ice_duration)))

mean_ice_cover
```

```{r}
#| fig-cap: Graph shows seasonal increases and decreases with a general decreasing trend over time. 
explor_icecover <- ggplot(data = mean_ice_cover, aes(x = year4,
                                                     y = mean_ice_duration)) +
  geom_point()

ggMarginal(explor_icecover, type = "densigram")

explor_icecover

```

```{r}
winter_air_temp <- weather_data |> 
  filter(month %in% c(12, 1, 2)) |> 
  group_by(year4) |> 
  summarize(mean_average_temp = round(mean(ave_air_temp_adjusted), 1))

winter_air_temp

explor_temp <- ggplot(data = winter_air_temp, aes(x = year4, 
                                                  y = mean_average_temp)) +
  geom_point() 

explor_temp
                        
```

